### PR TITLE
Nashville

### PR DESCRIPTION
**Pull request by blakerosenthal**
- Add `nearby_zones` step
- Add Nashville example
- Update to [Pandana 0.4](http://udst.github.io/pandana/index.html) (this requires also switching to Python 3)
- Buffering improvements
- Add more Pandana network options
  - can 'build' from a set of node/link files, 'read' from an H5 file, or 'download' from Open Street Maps
  - PSRC example uses 'build' as before. Nashville uses 'read'.
- also updated travis.yml to run properly

Note: this PR uses the upcoming ActivitySim 0.9.2 inputs API to read both CSVs and HDF5. DON'T MERGE until updating `activitysim >= 0.9.2` in setup.py. In the meantime, run `python setup.py develop` on [this](https://github.com/RSGInc/activitysim/tree/task_4) branch to use the new features.

### CODE REVIEW

**Comment by bstabler** [comment]
#1

**Comment by bstabler** [comment]
Looks good, a few todos:
- for example_nashville, drop buffering.csv and rename buffering_dvrpc.csv to buffering.csv
- update rst docs, explain the constants/settings such as max_pois, pois-x, pois-y, max_dist, etc.  What do these do?
- is max_dist used only for nearby_zones?  Should it be in a nearby_zones.yaml file then?  
- what is output by nearby_zones?  Can I save the table to csv?  Please add a setting to do so if desired.
- In daysim_files.yaml, change parcels_buffered.dat to nashville_maz_lu_buffered.dat
- In daysim_files.yaml, change corr_mznode.dat to ParcelNode.dat
- In daysim_files.yaml, change nodeskims_visum_text.dat to NodeDistances.dat
- In daysim_files.yaml, change nodeskims_visum_index.dat to NodeIndex.dat
- In daysim_files.yaml, add a delimiter argument for the output files since DaySim supports (ASCII code, 9=tab, 32=space, 44=comma)
- @nsdhakar test

Once we complete these, we can PR to https://github.com/psrc/netbuffer

**Comment by blakerosenthal** [comment]
Thanks for the review, @bstabler! I've updated the autodocs to describe each pipeline step, renamed the output filenames as above, and added a delimiter option to daysim_files.yaml.

The max_dist setting is used by the network builder, the nearby_zones step, and the buffer_zones step, which is why it's in the settings yaml rather than in each step's yaml. It must be the same value for all steps otherwise Pandana gets confused.

The nearby_zones step doesn't output anything. It just saves a table to the pipeline which can then be written via the write_daysim_files step.

**Comment by bstabler** [comment]
-  rename abm to processors, see https://github.com/RSGInc/netbuffer/tree/nashville/netbuffer/abm
- we want to use miles
  - input network coordinates are lat long and OSM is lat long
  - change osm link weights from meters to miles after getting them from the internet
  - calculate the latlong distances using geometry instead of the 110 approximation, see https://github.com/RSGInc/netbuffer/blob/b610217ccc63b79bca14ca616d58d6c061eb7e58/netbuffer/abm/models/nearby_zones.py#L73, https://stackoverflow.com/questions/27928/calculate-distance-between-two-latitude-longitude-points-haversine-formula, and https://gis.stackexchange.com/questions/142326/calculating-longitude-length-in-miles
  - fix this.  It should just be meters, but we're going to now make it miles, https://github.com/RSGInc/netbuffer/blob/nashville/netbuffer/core/network.py#L82
   - fix max_dist: 160 # in meters
   - do miles to feet, https://github.com/RSGInc/netbuffer/blob/nashville/netbuffer/abm/models/write_daysim_files.py#L111

**Comment by bstabler** [comment]
@blakerosenthal looks good, go ahead and merge once we fix the Travis issue

**Pull request merged**
